### ISSUE TITLE
There's a wrong link in the Testing Instructions on how to set up Zoiper

### ISSUE THREAD

**Issue by IlFriio** [aws-samples/amazon-transcribe-live-call-analytics#101]
https://github.com/aws-samples/amazon-transcribe-live-call-analytics/tree/develop -section - **Testing**, the readme link refers to the wrong page (https://github.com/aws-samples/amazon-transcribe-live-call-analytics/blob/develop/lca-chimevc-stack/README.md) INSTEAD OF the correct one at:  https://github.com/aws-samples/amazon-transcribe-live-call-analytics/blob/develop/lca-chimevc-stack/Asterisk.md

**Comment by rstrahan** [comment]
Thanks @IlFriio !  Link is now fixed..
