### ISSUE TITLE
CHIMEVCSTACK is failing

### ISSUE THREAD

**Issue by SridharSampath** [aws-samples/amazon-transcribe-live-call-analytics#11]
I can see CHIMEVCSTACK is failing, not sure why it is not able to create VPCInternetGateway and it is failing here
![VPCInternetGateway failed](https://user-images.githubusercontent.com/12897300/185393602-64611265-9c9f-4bc5-8cf9-00771275d3c0.PNG)
![EIPAssociation failed](https://user-images.githubusercontent.com/12897300/185393648-480e7717-2f5f-481b-aa2b-65919256b9e1.PNG)
![Capture](https://user-images.githubusercontent.com/12897300/185393669-f26b707d-5062-4446-9075-fb8779049dbd.PNG)

**Comment by rstrahan** [comment]
Not sure.. Looks like a permission issue. Does your role have admin permissions in your account? Does your account have service control policies (SCPs) that may be preventing the stack from creating an Internet Gateway resource?


From: SridharSampath ***@***.***>
Sent: Thursday, August 18, 2022 8:23 AM
To: aws-samples/amazon-transcribe-live-call-analytics ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [aws-samples/amazon-transcribe-live-call-analytics] CHIMEVCSTACK is failing (Issue #11)


I can see CHIMEVCSTACK is failing, not sure why it is not able to create VPCInternetGateway and it is failing here
[VPCInternetGateway failed]<https://user-images.githubusercontent.com/12897300/185393602-64611265-9c9f-4bc5-8cf9-00771275d3c0.PNG>
[EIPAssociation failed]<https://user-images.githubusercontent.com/12897300/185393648-480e7717-2f5f-481b-aa2b-65919256b9e1.PNG>
[Capture]<https://user-images.githubusercontent.com/12897300/185393669-f26b707d-5062-4446-9075-fb8779049dbd.PNG>

**Comment by SridharSampath** [comment]
Yeah I tried creating Internet Gateway alone, I got permission issue. So looks like it .

So closing the issue
