### ISSUE TITLE
Connect to a Amazon COnnect Instance

### ISSUE THREAD

**Issue by fbanespo1** [aws-samples/amazon-transcribe-live-call-analytics#115]
Hello,
I am trying to understand how to connect it to an existent Amazon Connect instance, without use Lens. I tried using Lens and the instance ARN but it doesn't pick up the live transcription, when I talk with an agent.

Can you help please?
Tony

**Comment by rstrahan** [comment]
Hi @fbanespo1 - Can you confirm if you have followed all the steps documented in the README: [Integrating the LCA solution with Amazon Connect](https://github.com/aws-samples/amazon-transcribe-live-call-analytics/blob/develop/lca-connect-integration-stack/README.md#integrating-the-lca-solution-with-amazon-connect)

**Comment by fbanespo1** [comment]
Hi @rstrahan - My apologies I missed a step that's won't work initially all good now.
Thanks
Tony

**Comment by rstrahan** [comment]
Great! Thanks for confirming.
