### ISSUE TITLE
Include Calude V3 Haiku in the BedrockModelId & AgentAssistQnABotLLMBedrockModelId

### ISSUE THREAD

**Issue by nmora53** [aws-samples/amazon-transcribe-live-call-analytics#129]
Hi team , It would be very useful to include Claude V3 Haiku in the BedrockModelId and in the AgentAssistQnABotLLMBedrockModelId. 
In Latin America we are having excellent results with that Model for Portuguese and Spanish.

**Comment by rstrahan** [comment]
Agree - I added it to our backlog.  
Meanwhile, if you'd like to contribute to the project, we'd certainly welcome a Pull Request for this enhancement :)

**Comment by rstrahan** [comment]
This will be in our next release.. Currently in develop branch.

**Comment by rstrahan** [comment]
We are also migrating from Amazon Kendra to Knowledge Bases on Amazon Bedrock.

**Comment by rstrahan** [comment]
Supported in v0.9.0
