### ISSUE TITLE
Live Meeting Assistant, doesn't log in transcriptions, if it has been sitting idle for long durations

### ISSUE THREAD

**Issue by ronykroy-aws** [aws-samples/amazon-transcribe-live-call-analytics#142]
Steps to reproduce
* login to Live Meeting Assistant, use it to transcribe a chime call
* remain logged in, after the above chime call ends, but attend/transcribe no other calls
* After about an hour plus, with the Live Meeting Assistant, still logged in if i click the 'start listening' button for a new chime call
* and then click on 'open in LMA' button, it takes me to the LMA meetings page, with the current meeting time stamp shown in the name, but nothin is getting transcribed.

Workaround:
relogin before the meeting to ensure LMA works as expected

Expected behaviour:
I should be able to start transcribing a new session without a hitch , as long as i have been logged in
the need for repeated logins sends users scurrying to enter passwords, click half a dozen buttons so on and so forth, that leaves users frustrated and deters usage of the tool

**Comment by rstrahan** [comment]
Hi @ronykroy-aws I think you mean to log this in the LMA repo (not the LCA repo)..  
Good news is I think we fixed it already in LMA - see https://github.com/aws-samples/amazon-transcribe-live-meeting-assistant/issues/35 
Closing here, but please do let us know over in LMA repo if there are still problems.
Cheers!
