### ISSUE TITLE
Include a cloudformation parameter to disable the audio and transcript recordings

### ISSUE THREAD

**Issue by juandag97** [aws-samples/amazon-transcribe-live-call-analytics#143]
Hello everyone, it would be very useful to have a cloudformation parameter to disable the audio and transcript recordings for Live Call Analytics, as far as we have seen, there they are two parameters related with the call recordings, but there it isn't a parameter to disable the audio and transcript recordings. How could we disable these call and transcript recordings?

<img width="1062" alt="Call-retention" src="https://github.com/aws-samples/amazon-transcribe-live-call-analytics/assets/40370372/ec212a7c-6057-44ed-b636-1c4919438cf7">

**Comment by rstrahan** [comment]
Hi @juandag97 - 

>to disable the audio and transcript recordings

Agree on having a parameter to disable audio recordings.

But can you clarify what you mean by 'disable transcript recordings'?   I am not clear what you mean by 'transcript recording' here.

Thanks Bob

**Comment by rstrahan** [comment]
@juandag97  gentle reminder on previous question..

**Comment by rstrahan** [comment]
Closing since there is no response on the thread.
