### ISSUE TITLE
One of my meetings using stream audio (no extension) feature is stuck in In Progress

### ISSUE THREAD

**Issue by syedair** [aws-samples/amazon-transcribe-live-call-analytics#145]
One of my meetings using stream audio (no extension) feature is stuck in **In Progress**.

I can't change the status to **Done**. Not sure if it will continue to consume resources. Ideally there should be an option in the meeting link to stop the meeting too.

Can someone help me how I can make this meeting stop? 

Attached is the screenshot:

<img width="1631" alt="image" src="https://github.com/aws-samples/amazon-transcribe-live-call-analytics/assets/20495779/09a13d10-0cc3-4641-bb57-c50582785b2a">

**Comment by rstrahan** [comment]
Hi @syedair - I think you meant to log this in the [Live Meeting Assistant repo](https://github.com/aws-samples/amazon-transcribe-live-meeting-assistant). Closing here, and please open it over there. Thanks!
