### ISSUE TITLE
Ability to retrieve audio from S3 bucket using call ID

### ISSUE THREAD

**Issue by tellis** [aws-samples/amazon-transcribe-live-call-analytics#150]
Is there a way to retrieve an audio file from the S3 bucket using the Call ID? We are using the stack to stream to our own client and arer missing this capability. I don't know if I am missing something but the call ID does not seem to be in the meta data.

**Comment by rstrahan** [comment]
Hi @tellis  - when the call has completed, the transcriber component sends an event [ADD_S3_RECORDING_URL](https://github.com/aws-samples/amazon-transcribe-live-call-analytics/blob/34faff30ce9a9f0517345d0265975bb375f3ce2e/lca-chimevc-stack/lambda_functions/call_transcriber/lca.js#L279) in the KDS stream to the Call Event processor, which mutates it into the AppSync schema as call metadata.. Appsync sends it to the UI client.  It's also persisted with the Call Record (PK = c#<callid>) in the DynamoDB event source table.. see screenshot.. 
![image](https://github.com/user-attachments/assets/caef70d8-4050-4c7f-a4af-18343b9bfd91)

I'm not sure where in the architecture you are integrating your own client, but hopefully this info helps. please confirm.

**Comment by rstrahan** [comment]
Closing due to lack of follow-up.

**Comment by tellis** [comment]
Sorry, I have been out of the office. Can you re-open the ticket?

We are using SIPREC to fork the audio stream from a Cisco VCube to Chime SDK Voice connector and the Audio processor is Chime SDK Voice Analytics. This was set up using standard configuration parameters in the Cloud Formation Template.
AgentAssist is not enabled as we are simply consuming the transcripts.

We are overwriting the Call ID  by implementing the SIPRECLambdaHook function. We have not otherwise altered the configuration.
On our client we are registering for the Transcription stream using the GraphQL API with the AppSyncAPI.

Everything works as expected for live call transcription but we would like al,so to retrieve the recordings and transcripts post-call.

Call transcripts are saved to the lca-call-analytics S3 bucket, but they are not identfied by call id.

We are not able to retrieve recordings through the GraphQL API.

In DynamoDB our record in EventSourcing Table looks like the following, with no RecordingUrl defined:
![Screenshot 2024-08-08 at 4 37 02 PM](https://github.com/user-attachments/assets/6ac925d8-fb35-4067-a99a-5fa9442a5c61)

Perhaps there is a parameter or setting we need to set but we have not been able to find it.

**Comment by rstrahan** [comment]
Yes, no problem reopening and thanks for the additional details.

I assume you have Transcribe API mode set to `analytics`, like this?
![image](https://github.com/user-attachments/assets/2d48a787-2632-42dc-98e2-60d4cd72e55a)

In your recordings bucket do you have 2 folders, like this? 
![image](https://github.com/user-attachments/assets/1a33113e-7be4-4908-9765-dfcab65d1b9b)

I think you are looking at the records nested below the `lca-call-analytics` folder.. If so, you are right - they are created by Transcribe Call Analytics some minutes after the call is over, and may be optionally redacted depending on your redaction settings - and they are not named with CallId.. instead they are named by Transcribe session Id which is not useful. At least not useful directly, however, LCA has the ability to make them useful via the `PCA Integration` feature.. I'll come back to that.

Since you said you are have Audio processor as `Chime SDK Voice Analytics` then I understand that you do not have recordings in the `lca-audio-wav` folder.. When Audio processor is `Transcriber Lambda` then we also create recordings there, based on the audio stream received.. these are the files I referred to above, that *are* named by CallId.


>In DynamoDB our record in EventSourcing Table looks like the following, with no RecordingUrl defined:
You should receive recording updates for the CallId record once they are written by Transcribe..  Not immediately sure why you are not.. They do take several minutes to arrive. Here's one of mine:  
![image](https://github.com/user-attachments/assets/659f034c-0e0c-41c7-9bd3-83bcf1680bc4)

I also have the PCA integration feature enabled.. Maybe there's a bug (undocumented feature) that causes recording updates to work only if PCA integration is enabled...

Anyway, can you enable PCA integration?  You don't actually need to deploy PCA!  Just create a bucket that you will use as the `PCA Input bucket` and provide values for the prefixes and the other params.. doesn;t matter if the URL is made up..

![image](https://github.com/user-attachments/assets/7e2c9a7d-e1ff-47ca-832e-13e8546c530d)

If all goes according to plan, LCA will create copies of both transcripts and audio files in this bucket, with CallId in their names, which you should be able to happily consume.  You might also find that the DynamoDB table is also updated (like mine).. 

Let me know what happens.

**Comment by tellis** [comment]
Hi Bob,

Thanks for the feedback and see *my answers and further questions* below.

On Thu, Aug 8, 2024 at 6:23 PM Bob Strahan ***@***.***> wrote:

> Yes, no problem reopening and thanks for the additional details.
>
> I assume you have Transcribe API mode set to analytics, like this?
>
*Yes. Transcribe is set to analytics*.

> image.png (view on web)
> <https://github.com/user-attachments/assets/2d48a787-2632-42dc-98e2-60d4cd72e55a>
>
> In your recordings bucket do you have 2 folders, like this?
> image.png (view on web)
> <https://github.com/user-attachments/assets/1a33113e-7be4-4908-9765-dfcab65d1b9b>
>
*No. I only see one folder*:
[image: image.png]




> I think you are looking at the records nested below the lca-call-analytics
> folder.. If so, you are right - they are created by Transcribe Call
> Analytics some minutes after the call is over, and may be optionally
> redacted depending on your redaction settings - and they are not named with
> CallId.. instead they are named by Transcribe session Id which is not
> useful. At least not useful directly, however, LCA has the ability to make
> them useful via the PCA Integration feature.. I'll come back to that.
>
> Since you said you are have Audio processor as Chime SDK Voice Analytics
> then I understand that you do not have recordings in the lca-audio-wav
> folder.. When Audio processor is Transcriber Lambda then we also create
> recordings there, based on the audio stream received.. these are the files
> I referred to above, that *are* named by CallId.
>
> In DynamoDB our record in EventSourcing Table looks like the following,
> with no RecordingUrl defined:
> You should receive recording updates for the CallId record once they are
> written by Transcribe.. Not immediately sure why you are not.. They do take
> several minutes to arrive. Here's one of mine:
> image.png (view on web)
> <https://github.com/user-attachments/assets/659f034c-0e0c-41c7-9bd3-83bcf1680bc4>
>
> *In our case they do not arrive*.


> I also have the PCA integration feature enabled.. Maybe there's a bug
> (undocumented feature) that causes recording updates to work only if PCA
> integration is enabled...
>
> Anyway, can you enable PCA integration? You don't actually need to deploy
> PCA! Just create a bucket that you will use as the PCA Input bucket and
> provide values for the prefixes and the other params.. doesn;t matter if
> the URL is made up..
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/7e2c9a7d-e1ff-47ca-832e-13e8546c530d>
>

*Is there a way I can do this without rerunning the CFT? The reason I ask
is that it is frequently used in our demo system and I would like to avoid
any risks or disruptions.*

*I have also noticed that Post-call Analytics is not enabled in Transcribe.
Should this be enabled?*
[image: image.png]

If all goes according to plan, LCA will create copies of both transcripts

**Comment by rstrahan** [comment]
> Is there a way I can do this without rerunning the CFT?

Not really, unless you want to get deep in the weeds to hack the effects of the CFT - eg manually set function env vars and more, which I don't recommend.  Updating the stack using CFT is the easiest way, and the only way I can support you.
Cheers
Bob


Sent from Workspace ONE Boxer

On Aug 13, 2024 12:28 PM, tellis ***@***.***> wrote:

Hi Bob,

Thanks for the feedback and see *my answers and further questions* below.

On Thu, Aug 8, 2024 at 6:23 PM Bob Strahan ***@***.***> wrote:

> Yes, no problem reopening and thanks for the additional details.
>
> I assume you have Transcribe API mode set to analytics, like this?
>
*Yes. Transcribe is set to analytics*.

> image.png (view on web)
> <https://github.com/user-attachments/assets/2d48a787-2632-42dc-98e2-60d4cd72e55a>
>
> In your recordings bucket do you have 2 folders, like this?
> image.png (view on web)
> <https://github.com/user-attachments/assets/1a33113e-7be4-4908-9765-dfcab65d1b9b>
>
*No. I only see one folder*:
[image: image.png]




> I think you are looking at the records nested below the lca-call-analytics
> folder.. If so, you are right - they are created by Transcribe Call
> Analytics some minutes after the call is over, and may be optionally
> redacted depending on your redaction settings - and they are not named with
> CallId.. instead they are named by Transcribe session Id which is not
> useful. At least not useful directly, however, LCA has the ability to make
> them useful via the PCA Integration feature.. I'll come back to that.
>
> Since you said you are have Audio processor as Chime SDK Voice Analytics
> then I understand that you do not have recordings in the lca-audio-wav
> folder.. When Audio processor is Transcriber Lambda then we also create
> recordings there, based on the audio stream received.. these are the files
> I referred to above, that *are* named by CallId.
>
> In DynamoDB our record in EventSourcing Table looks like the following,
> with no RecordingUrl defined:
> You should receive recording updates for the CallId record once they are
> written by Transcribe.. Not immediately sure why you are not.. They do take
> several minutes to arrive. Here's one of mine:
> image.png (view on web)
> <https://github.com/user-attachments/assets/659f034c-0e0c-41c7-9bd3-83bcf1680bc4>
>
> *In our case they do not arrive*.


> I also have the PCA integration feature enabled.. Maybe there's a bug
> (undocumented feature) that causes recording updates to work only if PCA
> integration is enabled...
>
> Anyway, can you enable PCA integration? You don't actually need to deploy
> PCA! Just create a bucket that you will use as the PCA Input bucket and
> provide values for the prefixes and the other params.. doesn;t matter if
> the URL is made up..
>
> image.png (view on web)
> <https://github.com/user-attachments/assets/7e2c9a7d-e1ff-47ca-832e-13e8546c530d>
>

*Is there a way I can do this without rerunning the CFT? The reason I ask
is that it is frequently used in our demo system and I would like to avoid
any risks or disruptions.*

*I have also noticed that Post-call Analytics is not enabled in Transcribe.
Should this be enabled?*
[image: image.png]

If all goes according to plan, LCA will create copies of both transcripts

**Comment by tellis** [comment]
Ok, thanks. I will try that but will hold off until I have a window.

**Comment by rstrahan** [comment]
Hi @tellis - just checking in to see if you were able to resolve this one?

**Comment by tellis** [comment]
Hi Bob,
I still have not had time to rerun the CFT as the demo is in frequent use
and I need to ensure that I can recover from any changes.

There have been some other issues including doubling of transcriptions
entries (same utterance showing up twice in the EventsourcingTable records)
and two sets of recordings and transcripts in the lca-call-analytics folder
.So we definitely need to do a reset.

Regards,

Tim

**Comment by rstrahan** [comment]
> There have been some other issues including doubling of transcriptions
entries (same utterance showing up twice in the EventsourcingTable records)
and two sets of recordings and transcripts in the lca-call-analytics folder

Interesting.. that's unusual. Feel free to log a new Issue if you need help tracking that one down.  
Initial things to check are (a) audio - is there clean channel separation - ie check that the two channels are not duplicating same audio  (b) duplicate Voice Connectors handling the same call.

**Comment by rstrahan** [comment]
@tellis I'm going to close the issue now, pending your additional investigation / new issue as discussed above. Feel free to reopen when you have additional testing and data to share. Thanks!

**Comment by tellis** [comment]
OK. I will reopen when this becomes an issue for users.
