### ISSUE TITLE
Mic input role (CALLER vs. AGENT) assignment not working

### ISSUE THREAD

**Issue by babu-srinivasan** [aws-samples/amazon-transcribe-live-call-analytics#169]
**Description:**
Changing the role (CALLER vs. AGENT) for mic input does not make any difference in the label assignment. 

**Screenshots**
<img width="1310" alt="Screenshot 2024-08-02 at 5 22 45 PM" src="https://github.com/user-attachments/assets/710debcf-13f6-4d0e-a48f-238e3cd02880">
<img width="1309" alt="Screenshot 2024-08-02 at 5 22 53 PM" src="https://github.com/user-attachments/assets/7d547539-f5d5-472b-a000-46e4f712406d">

**Steps to reproduce the issue:**
1/ From "Stream Audio" tab, choose CALLER from the "Microphone Role" dropdown
2/ Speak into the microphone
3/ Check the turn-by-turn transcriptions - the label assigned to the transcriptions of audio from mic input is "AGENT" (this should be "CALLER"

**LCA Version with the issue**
8.13 (public version from lca github repo)

**Comment by babu-srinivasan** [comment]
Proposed Fix:
In StreamAudio.jsx, check micInputOption.value. Based on the value (agent vs. caller), setup the channel merger inputs.

**Comment by rstrahan** [comment]
Fixed in v0.9.0
