### ISSUE TITLE
CF Template doesn't work with Genesys

### ISSUE THREAD

**Issue by dmartinezrubio** [aws-samples/amazon-transcribe-live-call-analytics#207]
I’m receiving this error (using Genesys).

<img width="1025" alt="code-build" src="https://github.com/user-attachments/assets/b29d7433-5cfc-4093-b431-848ab2120df1">

It seems a problem with the code

<img width="698" alt="error" src="https://github.com/user-attachments/assets/f577a540-acee-4271-8098-c3acd8a279b2">

**Comment by rstrahan** [comment]
Fixed in v0.9.4
