### ISSUE TITLE
Allow to use an existing VPC service as an optional parameter in the CloudFormation template

### ISSUE THREAD

**Issue by diego-santamaria** [aws-samples/amazon-transcribe-live-call-analytics#78]
Hello,

I think having the option to use an existing VPC service, subnets, route tables, and internet gateway would be useful, especially when VPCs are centrally managed (shared).

I understand the scope is to keep this deployment separate from the rest of the existing VPC, but I'm wondering if this request is achievable?

Thank you.

**Comment by rstrahan** [comment]
Hi @diego-santamaria - It's certainly do-able, and thanks for the suggestion.. However, it honestly not likely to make it to top of priority list any time soon.   Can you fork the repo, and make the template changes you need to deploy into your own existing VPC / subnets?
