### ISSUE TITLE
Urgent Issue with Call Transcription: Inconsistent Behavior Observed

### ISSUE THREAD

**Issue by tarungupta83** [aws-samples/amazon-transcribe-live-call-analytics#94]
Hi LCA Team,

We're building a solution tailored for a large enterprise using the specified stack. Our current implementation successfully transcribes 60% of the calls. However, the remaining 40% persistently show a status of "In-Progress", and we don't receive any transcripts or audio for these calls.

Upon investigation, our logs indicate that we might not be sending the 'opened' packet within the 5-second timeout window as expected by Genesys. This is perplexing given that 60% of the calls work without any hitches.

We're keen on understanding if our application on Fargate is functioning optimally. We've attached relevant screenshots and logs for your review (note: any PII has been redacted).

Could you assist us in pinpointing the exact error and provide guidance on resolving this inconsistency? 
We've also received a response from Genesys, attached for reference.

---
{
	"timestamp": "PT5.581928956S",
	"type": "audiohook",
	"data": {
		"dir": "in",
		"message": {
			"version": "2",
			"id": "dummy",
			"type": "error",
			"seq": 2,
			"position": "PT0.0S",
			"parameters": {
				"code": 408,
				"message": "Timed out waiting for opened response"
			},
			"serverseq": 0
		}
	}
},
![image](https://github.com/aws-samples/amazon-transcribe-live-call-analytics/assets/5612569/c5c62f4f-71d2-4874-8f1d-d552575ec34c)
**(can share the logs for more help)**

**Comment by babu-srinivasan** [comment]
Hi tarungupta83,
Thanks for reporting the issue. Could you please share the response from Genesys and the logs. Meanwhile, I will try to re-create the issue on my side to debug. 

What is the maximum number of calls that are in progress at any given point in time i.e. (number of concurrent sessions)? 

Thanks,

**Comment by tarungupta83** [comment]
Thank you for your response. Currently, the number of concurrent calls fluctuates between 1 and 6.

Given that the solution resides within our organization's account, sharing CloudWatch logs on a public forum presents challenges. However, I've attached sanitized logs from the Fargate Application with personal data redacted. We're willing to provide the logs directly via email. If you could provide an official email address, it would facilitate our sharing of the necessary details.
 
[logs.zip](https://github.com/aws-samples/amazon-transcribe-live-call-analytics/files/12562409/logs.zip)

**Comment by tarungupta83** [comment]
Hi Babu Srinivasan,
 
Here are some additional observations:
1. It appears that Fargate is not responding with an "opened" message to Genesys within the 5-second timeout window. (From the Genesys "open" to the "LCA opened" response).
2. In certain cases, Genesys initiated a reconnect when the Fargate Application didn't send the "opened" message. On the subsequent try, Fargate managed to send the "opened" message, allowing the connection to be established and the call to proceed successfully.
3. Calls that didn't experience a reconnect attempt from Genesys ended up failing.

**Comment by babu-srinivasan** [comment]
Thanks for sharing the redacted logs and the additional observations. 
I have observed something similar only when testing high volume of concurrent calls - ie. I was hitting the soft limits on concurrent sessions for Transcribe streaming in the AWS account I was testing with. But, in your case, it looks like you are only testing a small number of calls. 

The audiohook server (fargate) returns 'opened' message after running all the open handlers. One of the key open handlers establishes streaming session with Transcribe.  Could you please check the logs for those calls that failed (to ensure Transcribe session is established properly)
1/ check the logs to see if you have any of the following messages (this means the session with Transcribe was established successfully). 
"=== Received Initial response from TCA. Session Id:"  or 
"=== Received Initial response from Transcribe. Session Id:"

2/ Check the logs for any Transcribe related errors. 


Thanks

**Comment by tarungupta83** [comment]
No when call fails we do not see any message w.r.t transcription.

Rather after open message we only see, error msg coming from genesys.

I have already shared more than 7 error logs and 1 log for completed call.

Can you point out where exactly we send opened msg, as I do not see any
reason  why we don't send opened msg as a response to open

**Comment by tarungupta83** [comment]
Hi @babu-srinivasan/@rstrahan,

Thank you for assisting with the identified issue. I've provided the CloudWatch logs as requested.

As part of our roadmap, we're gearing up to deploy the complete stack for a client. We anticipate around 20 million calls annually. Your support on this issue is crucial for us.

Additionally, we're interested in availing extended support from AWS. Given that we already hold an enterprise account with AWS, could you guide us on how to officially reach out for this extended service?

Best regards,
Tarun
+919810698355
[CloudWatch_log_failed_Call.txt](https://github.com/aws-samples/amazon-transcribe-live-call-analytics/files/12575935/CloudWatch_log_failed_Call.txt) - Redacted Logs

**Comment by babu-srinivasan** [comment]
I have sent you an email to follow-up. Thanks!

**Comment by rstrahan** [comment]
@babu-srinivasan @tarungupta83  What's the status of this issue?

**Comment by tarungupta83** [comment]
This issue is broadly solved, We did changed the setup, while we also updated the code to latest version available. After that we are not facing issues w.r.t call drop.

A small question I would like to ask, can we add multiple TRANSCRIPT_LAMBDA_HOOK_FUNCTION_ARN lambda functions to work parallelly for updating transcript.

**Comment by rstrahan** [comment]
> This issue is broadly solved
Awesome.. I'll resolve this and the other related open issue #95

> A small question I would like to ask, can we add multiple TRANSCRIPT_LAMBDA_HOOK_FUNCTION_ARN lambda functions to work parallelly for updating transcript.

Not currently.. Only one Arn can be provided/invoked, but of course your Lambda can do whatever you want, including invoking additional custom Lambda functions... _to work parallelly for updating transcript_

Good luck, and thanks for using LCA!

**Comment by rajapradeep** [comment]
I am also facing the same issue. How exactly was it resolved. Can you explain @tarungupta83 @rstrahan @babu-srinivasan.
