### ISSUE TITLE
LCA Audio Hook not able to send Opened Message within 5 Sec

### ISSUE THREAD

**Issue by tarungupta83** [aws-samples/amazon-transcribe-live-call-analytics#95]
Hello Team,

Following up on the previous issue, we're experiencing delays with the LCA Audio Hook. It seems not to consistently send the "opened" message within the expected 5-second timeframe, as required by Genesys Audio Hook.

Our observations indicate that:
- About 50% of the time, the Genesys Audiohook to LCA (FarGate) doesn't send the "opened" message in response to the "open" message from Genesys Audio Hook.
- In 20-30% of cases, Genesys attempts to reconnect to LCA by resending the "open" message. On these second attempts, LCA typically responds with the "opened" message. However, when Genesys Audio Hook only makes a single attempt, the call usually fails.

Could you provide insight into the soft and hard limits for websocket connections? We're trying to understand why, on singular attempts, LCA fails to acknowledge the "open" message with an "opened" response.

I've attached the CloudWatch logs sent on email.

Best regards,
Tarun

**Comment by rstrahan** [comment]
@babu-srinivasan @tarungupta83  What's the status of this issue?

**Comment by rstrahan** [comment]
Closed as related to #94
