### ISSUE TITLE
Connect Integration Stack with LCA doesn't identify the categories etc.

### ISSUE THREAD

**Issue by pkawssa** [aws-samples/amazon-transcribe-live-call-analytics#98]
Hello, Connect Integration Stack with LCA doesn't identify the categories etc. The call_event_processor.py (lca-ai-stack/source/lambda_functions/call_event_processor/event_processor/call_event_processor.py => ‎add_contact_lens_call_category function) logic for identifying the category when integrated with Connect using Contact Lens streaming isn't working as expected. The category identified by the CL is sent to the lambda but it fails to process and update the appsync/dynamo db. Please review and update the lambda.
Thanks!

**Comment by rstrahan** [comment]
Resolved in  v0.8.7.  Thanks for reporting this issue @pkawssa
